#!/bin/bash
cd /usr/local/src && apt install wget -y
wget https://it-services.c-rieger.de/s/QCzDbdip4qM388P/download -O install.zip
wget https://it-services.c-rieger.de/s/kX56nntHoWWoPps/download -O install.zip
apt install unzip -y && unzip install.zip
chmod +x install.sh
./install.sh
